### ISSUE TITLE
4x upsampling

### ISSUE THREAD

**Issue by cyun-404** [danielTobon43/upsamplingCloudPCL#5]
I was able to perform pcl upsampling. Thank you. 

I'd like to do 4x upsampling, have you ever done any related work? How should I set the rate?

**Comment by ghost** [comment]
Hi @cyun-404. I am glad it works. Well, a silly approach would be to run the program twice with the output cloud so that you will get by x4 upsampling. But, if you increase the `--sampling-radius ` parameter, this will increase the number of sampled points, although this will also increase the processing time and could take longer to generate the output cloud.

**Comment by cyun-404** [comment]
I'll try all the methods you told me! Thank you so much!!
